#      ___                            _    ___        _
#    / __> _ _  ___  ___  ___  _ _ _| |_ | . > ___ _| |_
#     \__ \| | || . \| . \/ . \| '_> | |  | . \/ . \ | |
#     <___/`___||  _/|  _/\___/|_|   |_|  |___/\___/ |_|
#                |_|  |_|
#
#           SupportBot created by Emerald Services
#           Installed with MIT License
#
#           Discord Support: https://discord.gg/emeraldsrv
#           Official Documentation: https://docs.emeraldsrv.com
#           Addons Marketplace: https://community.emeraldsrv.com
#
#           SupportBot Configuration (supportbot.yml)

SupportBot_Version: "v8.3"

# -------------------------
#   General
# -------------------------

General:
  Name: "SupportBot"
  Token: "BOT_TOKEN"

  Addons:
    Enabled: true
    
# -------------------------
#  Activity
# -------------------------

Activity:
  Status: "SupportBot v8"
  Type: "Competing"
  StreamingURL: "https://www.twitch.tv/YOUR_TWITCH_NAME"

  # Available Types:
  # Playing
  # Watching
  # Listening
  # Competing
  # Streaming (URL required)

  # You can also update the activity via Discord using: /settings

# -------------------------
#  Embeds
# -------------------------

Embed:
  Colours:
    General: 0x0cc559
    Success: 0x04b545
    Error: 0xd13030
    Warn: 0xfca117

  Footer: "SupportBot | Developed by Emerald Development"

  # Use 0x<hexcode>  to change the colour of the embeds.

# -------------------------
#  Roles
# -------------------------

Roles:
  AutoRole:
    Enabled: true
    Role: "ROLE_ID"

  StaffMember:
    Staff: "ROLE_ID"
    Admin: "ROLE_ID"
    Moderator: "ROLE_ID"

  Mod:
    AllowSupportStaff: false

  # Allow Support Staff to use the /mod command. (More in detail customisation in commands.yml)

# ----------------------------
#  System Messages
# ----------------------------

Welcome: 
  Enabled: true
  Channel: "JOIN_CHANNEL_ID"

Leave: 
  Enabled: true
  Channel: "JOIN_CHANNEL_ID"

# ----------------------------
#  Suggestions
# ----------------------------

Suggestions:
  Channel: "SUGGESTIONS_CHANNEL_ID"
  UpvoteEmoji: "✅"
  DownvoteEmoji: "❌"

  UpvoteTitle: "Yes"
  DownvoteTitle: "No"

  OwnSuggestion: true

  # If false this will not allow the user to vote for a suggestion they created
  # If true this will allow the user to vote for a suggestion they created

  ShowUsers: true
  
  Threads:
    Enabled: true
    Title: "Suggestion-releated Thread"
    Reason: "A thread releted to this suggestion"

  Buttons:
    Upvote: "2"
    Downvote: "2"
    RemoveVote: "4"
    RemoveVote_Title: "Remove Vote"

    # Available Button Styles
    # 1 - Blurple
    # 2 - Grey
    # 3 - Green
    # 4 - Red

# -------------------------
#  Tickets
# -------------------------

VoiceTickets:
  Name: "%username%'s VC" 
  Category: "VOICEE_CATEGORY_ID"

Ticket:
  TicketType: "channels" 

  # Available TicketTypes:
  # channels - Tickets will be created as channels in the TicketChannelsCategory
  # threads - Tickets will be created as threads through the "TicketHome" channel.

  TicketHome: "TICKETHOME_CHANNEL_ID" 

  # What is TicketHome?
  # - Channel where the Ticket creation panel is sent.
  # - Channel where ticket threads are made. (only if ticket threads is enabled above.)

  # For TicketType: channels
  TicketChannelsCategory: "TICKETCHANNEL_CATEGORY_ID" 
  TicketChannelsCategory2: "TICKETCHANNEL_BACKUP_CATEGORY_ID" # This will be used if the first category has reached the max channel limit.
  TicketArchiveCategory: "ARCHIVE_CATEGORY_ID"
  # ---

  Channel: "ticket-" # The prefix for ticket channel names
  TicketsPerUser: 100
  DMTranscripts: true
  TicketReason: true
  # If ticket reason is set to false, It will not prompt to create a reason

  TicketSubject: "description"

  # Available TicketSubjects:
  # "description" will display the ticket reason within the channel description
  # "embed" will display the ticket reason within the ticket embed

  Timeout: 5
  # Set to true to allow all staff to access the ticket

  Close:
    StaffOnly: true
    # Set to false is anyone is able to close a ticket.

    Confirmation_Button: "Confirm Close"
    Confirmation_Emoji: "🗑️"
    Confirmation_Style: "2"

    Title: "Are you sure you want to close this ticket?"

    # Available Button Styles:
    # 1 - Blurple
    # 2 - Grey
    # 3 - Green
    # 4 - Red

  Invites:
    StaffOnly: true

  ClaimTickets:
    Enabled: true
    Channel: "CLAIM_TICKETS_CHANNEL_ID" 
    # Channel where the ticket assignments are sent for staff to claim.
    
    ClaimAcceptTime: 120000
    # How long the assigned user has to accept the ticket before it gets re-assigned to someone else.
    # 120000 = 2 Minutes
    # 180000 = 3 Minutes
    # 240000 = 4 Minutes
    # 300000 = 5 Minutes
    # Time in Mliseconds

    ButtonTitle: "Claim Ticket"
    ButtonEmoji: "🎫"
    Button: "1"

    # Available Button Styles
    # 1 - Blurple
    # 2 - Grey
    # 3 - Green
    # 4 - Red

  ReviewSystem:
    Enabled: true                
    Channel: "REVIEW_CHANNEL_ID"
    UseModal: true

  Questions:
    Enabled: true  # Set to false to disable ticket questions
    List:
      - "Please provide your account email?"
      - "What is the nature of your issue?"
      - "Have you tried resolving the issue yourself?"

  Log:
    TicketDataLog: "TICKET_DATA_LOG_ID"
    TickeDataTitle: "Ticket Data"
    TicketBlacklistLog: "TICKET_BLACKLIST_LOG_ID"

# -------------------------
#  Buttons
# -------------------------
Buttons:
  General:
    Delete: "🗑️"
    DeleteStyle: "4"

  Voice:
    TicketDeleteText: "Delete Voice Channel"

  Tickets:
    ClaimEmoji: "🧑‍💻"
    ClaimStyle: "1"

    Unarchive: "Unarchive Ticket"
    Unarchive_Emoji: "♻️"
    Unarchive_Style: "2"

    Unlock: "Unlock Ticket"
    Unlock_Emoji: "🔓"
    Unlock_Style: "2"

    # Available Button Styles
    # 1 - Blurple
    # 2 - Grey
    # 3 - Green
    # 4 - Red

# -------------------------
#  Select Menus
# -------------------------

SelectMenus:
  Tickets:
    PanelEmoji: "⚙️"
    
    CloseEmoji: "🗑️"
    ArchiveEmoji: "♻️"
    LockEmoji: "🔐"
    RenameEmoji: "🏷️"
    VCEmoji: "🔊"

    EnableInvitesEmoji: "📤"
    DisableInvitesEmoji: "📥"

# -------------------------
#  Logging
# -------------------------

MessageDelete:
  Channel: "MESSAGE_DELETE_CHANNEL_ID""
  Colour: "#d92525"

MessageUpdate:
  Channel: "MESSAGE_UPDATE_CHANNEL_ID"
  Colour: "#f2a024"

Translate:
  TranslateLog: "TRANSLATE_LOG_ID"
